<a href="https://colab.research.google.com/github/JyothiNandhan/SpeechProcessing/blob/main/EmotionRecognition_LSTM_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
!kaggle datasets download -d ejlok1/toronto-emotional-speech-set-tess

Dataset URL: https://www.kaggle.com/datasets/ejlok1/toronto-emotional-speech-set-tess
License(s): Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
100% 428M/428M [00:16<00:00, 33.3MB/s]
100% 428M/428M [00:16<00:00, 28.0MB/s]


In [ ]:
import zipfile
zip_ref=zipfile.ZipFile('/content/toronto-emotional-speech-set-tess.zip')
zip_ref.extractall('/content/drive/MyDrive/Emotion_Recog')
zip_ref.close()

In [2]:
import glob
voice=glob.glob('/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/**/*.wav',recursive=True)
print(voice)
print(len(voice))

['/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_back_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_bar_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_base_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_bath_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_bean_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_beg_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_bite_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_boat_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_bone_fear.wav', '/content/drive/MyDrive/Emotion_Recog/TESS Toro

In [2]:
import os
os.listdir('/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data')

['OAF_Fear',
 'OAF_Pleasant_surprise',
 'OAF_Sad',
 'OAF_angry',
 'OAF_disgust',
 'OAF_happy',
 'OAF_neutral',
 'YAF_angry',
 'YAF_disgust',
 'YAF_fear',
 'YAF_happy',
 'YAF_neutral',
 'YAF_pleasant_surprised',
 'YAF_sad']

In [5]:
import librosa
import random
import numpy as np
import glob
features=[]
labels=[]
emotions=['OAF_Fear',
 'OAF_Pleasant_surprise',
 'OAF_Sad',
 'OAF_angry',
 'OAF_disgust',
 'OAF_happy',
 'OAF_neutral',
 'YAF_angry',
 'YAF_disgust',
 'YAF_fear',
 'YAF_happy',
 'YAF_neutral',
 'YAF_pleasant_surprised',
 'YAF_sad']


for spk in emotions:
  voice=glob.glob(f'/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/{spk}/**/*.wav',recursive=True)
  # print(voice)
  # r=random.sample(voice,10)
  # print(r,end='\n')
  # break
  for audio in voice:
  # r=random.sample(voice,10)
    y,sr=librosa.load(audio)
    mfccs=librosa.feature.mfcc(y=y,n_mfcc=13,sr=sr)
    mfccs=mfccs.T
    features.append(mfccs)
    labels.append(spk)
max_length = max(f.shape[0] for f in features)
padded_features=[np.pad(f,((0,max_length-f.shape[0]),(0,0)),mode='constant')for f in features]










In [7]:
import numpy as np
x=np.array(padded_features)
y=np.array(labels)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y= label_encoder.fit_transform(y)



In [8]:
print(y)
len(y)

[ 0  0  0 ... 13 13 13]


2800

In [9]:
x.shape

(2800, 129, 13)

In [10]:
y.shape

(2800,)

In [8]:
from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
X_train.shape

(2240, 129, 13)

In [10]:
y_train.shape

(2240,)

In [11]:
y_test.shape

(560,)

In [12]:
segments=X_train.shape[1]
features=X_train.shape[2]

In [13]:
y_train

array([11,  5,  9, ...,  9,  0,  9])

In [14]:
y_test

array([13, 12, 13, 12,  6,  3,  5,  1,  4,  8, 11,  8,  2,  4, 13,  7,  8,
       11,  4,  4, 10, 11, 12,  6, 13,  9,  1,  3,  3, 13,  2,  2,  4,  8,
        8,  1, 11,  6, 12,  7,  8, 11, 13,  6, 11,  3, 11,  5, 12, 12,  2,
        7, 12,  1,  3, 12,  2, 11,  7,  6, 13,  1,  2,  1,  4,  7,  2,  4,
       10,  4,  9,  0, 11,  0,  1, 12,  4,  8,  0, 10,  1, 10,  0,  2, 11,
       11,  0, 13,  1,  0,  7,  5,  1,  5,  4, 10,  0,  5, 11,  9,  9, 13,
        8,  6, 11, 12,  7, 10,  7,  9,  5,  0,  5,  4,  9,  3,  5, 11,  3,
       11,  2,  3,  4,  6,  8,  8, 11,  6,  6, 11,  7, 10,  4,  2, 12,  4,
        7,  2,  4, 12, 10,  9,  0, 13,  8,  8, 10,  7,  3,  4, 10,  6,  4,
        8, 11,  7,  0,  9,  3, 13,  2,  4,  1,  8,  8,  4,  8, 10, 11, 12,
        2,  7,  4, 10,  5,  4,  4,  4,  6, 11,  5, 13, 13,  8,  5, 13,  9,
        3,  0,  5,  8,  2, 10, 11,  7,  7, 11,  5, 11, 12,  9,  1,  9,  2,
        9, 10, 13, 10, 12,  2,  0, 10,  7,  2,  3, 11,  3, 10,  2,  2,  4,
        9,  7,  1,  8,  3

In [17]:
from tensorflow import keras

# Assuming X_train, X_test, y_train are defined

# Reshape input data
X_train = X_train.reshape(-1, segments, features)
X_test = X_test.reshape(-1, segments, features)

# Define the model
model = keras.Sequential()
model.add(keras.layers.LSTM(64, input_shape=(segments, features), return_sequences=True))
model.add(keras.layers.LSTM(64))
# model.add(keras.layers.BatchNormalization())
# model.add(keras.layers.LSTM(64))
# model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dropout(0.1))
model.add(keras.layers.Dense(14, activation='softmax'))

# Compile the model
optimiser = keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# early_stopping = keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Print model summary
model.summary()

# Train the model
history = model.fit(X_train, y_train, epochs=60, batch_size=32)


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 129, 64)           19968     
                                                                 
 lstm_5 (LSTM)               (None, 64)                33024     
                                                                 
 dense_4 (Dense)             (None, 64)                4160      
                                                                 
 dropout_2 (Dropout)         (None, 64)                0         
                                                                 
 dense_5 (Dense)             (None, 14)                910       
                                                                 
Total params: 58062 (226.80 KB)
Trainable params: 58062 (226.80 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/60
70/70

In [18]:
test_loss,test_acc=model.evaluate(X_test,y_test)
print('\nTest accuracy:',test_acc)

18/18 [==============================] - 2s 39ms/step - loss: 0.1636 - accuracy: 0.9589

Test accuracy: 0.9589285850524902


In [19]:
model.save("/content/drive/MyDrive/Emotion_Recog/Emotion_recognition.keras")

In [1]:
from tensorflow.keras.models import load_model
model=load_model('/content/drive/MyDrive/Emotion_Recog/Emotion_recognition.keras')

In [7]:
emotions=['OAF_Fear',
 'OAF_Pleasant_surprise',
 'OAF_Sad',
 'OAF_angry',
 'OAF_disgust',
 'OAF_happy',
 'OAF_neutral',
 'YAF_angry',
 'YAF_disgust',
 'YAF_fear',
 'YAF_happy',
 'YAF_neutral',
 'YAF_pleasant_surprised',
 'YAF_sad']


In [8]:
import librosa
import numpy as np
from tensorflow import keras

path = "/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_bar_fear.wav"
audio, sr=librosa.load(path)
mfccs = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)
print(f"Original MFCC shape: {mfccs.shape}")
features = mfccs.T
print(f"Transposed MFCC shape: {features.shape}")
timesteps = 129
num_features = 13
if features.shape[0] < timesteps:
    pad_width = timesteps - features.shape[0]
    features = np.pad(features, ((0, pad_width), (0, 0)), mode='constant')
else:
    features = features[:timesteps, :]

print(f"Padded MFCC shape: {features.shape}")
features = features.reshape(1, timesteps, num_features)
print(f"Final input shape: {features.shape}")

predictions = model.predict(features)
predicted_label = np.argmax(predictions)
predicted_class = emotions[predicted_label]

print("Predicted class:", predicted_class)

Original MFCC shape: (13, 73)
Transposed MFCC shape: (73, 13)
Padded MFCC shape: (129, 13)
Final input shape: (1, 129, 13)
1/1 [==============================] - 0s 68ms/step
Predicted class: OAF_Fear


# **CNN**

In [2]:
import librosa
import random
import numpy as np
import glob
features=[]
labels=[]
emotions=['OAF_Fear',
 'OAF_Pleasant_surprise',
 'OAF_Sad',
 'OAF_angry',
 'OAF_disgust',
 'OAF_happy',
 'OAF_neutral',
 'YAF_angry',
 'YAF_disgust',
 'YAF_fear',
 'YAF_happy',
 'YAF_neutral',
 'YAF_pleasant_surprised',
 'YAF_sad']


for spk in emotions:
  voice=glob.glob(f'/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/{spk}/**/*.wav',recursive=True)

  for audio in voice:
    y,sr=librosa.load(audio)
    mels=librosa.feature.melspectrogram(y=y,n_mels=128,sr=sr,)
    mels=mels.T
    features.append(mels)
    labels.append(spk)
max_length = max(f.shape[0] for f in features)
padded_features=[np.pad(f,((0,max_length-f.shape[0]),(0,0)),mode='constant')for f in features]










In [3]:
import numpy as np
x=np.array(padded_features)
y=np.array(labels)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y= label_encoder.fit_transform(y)

In [4]:
from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
segments=X_train.shape[1]
features=X_train.shape[2]

In [8]:
from tensorflow import keras

# Assuming X_train, X_test, y_train are defined

# Reshape input data
X_train = X_train.reshape(-1, segments, features)
X_test = X_test.reshape(-1, segments, features)

# Define the model
model = keras.Sequential()
model.add(keras.layers.Conv2D(32,(3,3),activation='relu',input_shape=(segments,features,1)))
model.add(keras.layers.MaxPooling2D(2,2))
# model.add(keras.layers.Conv2D(32,(3,3),activation='relu'))
# model.add(keras.layers.MaxPooling2D(2,2))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(64,activation='relu'))
model.add(keras.layers.Dropout(0.1))
model.add(keras.layers.Dense(14,activation='softmax'))



# Compile the model
optimiser = keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
early_stopping = keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Print model summary
model.summary()


# Train the model
history = model.fit(X_train, y_train, epochs=60, batch_size=32,validation_data=(X_test,y_test),callbacks=[early_stopping])

test_loss,test_acc=model.evaluate(X_test,y_test)
print("Test Accuracy:",test_acc)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 127, 126, 32)      320       
                                                                 
 max_pooling2d_6 (MaxPoolin  (None, 63, 63, 32)        0         
 g2D)                                                            
                                                                 
 flatten_3 (Flatten)         (None, 127008)            0         
                                                                 
 dense_6 (Dense)             (None, 64)                8128576   
                                                                 
 dropout_3 (Dropout)         (None, 64)                0         
                                                                 
 dense_7 (Dense)             (None, 14)                910       
                                                      

In [13]:
emotions=['OAF_Fear',
 'OAF_Pleasant_surprise',
 'OAF_Sad',
 'OAF_angry',
 'OAF_disgust',
 'OAF_happy',
 'OAF_neutral',
 'YAF_angry',
 'YAF_disgust',
 'YAF_fear',
 'YAF_happy',
 'YAF_neutral',
 'YAF_pleasant_surprised',
 'YAF_sad']


In [15]:
import librosa
import numpy as np
from tensorflow import keras

path = "/content/drive/MyDrive/Emotion_Recog/TESS Toronto emotional speech set data/OAF_Fear/OAF_bar_fear.wav"
audio, sr=librosa.load(path)
mels = librosa.feature.melspectrogram(y=audio, sr=sr, n_mels=128)
print(f"Original MFCC shape: {mels.shape}")
features = mels.T
print(f"Transposed MFCC shape: {features.shape}")
timesteps = 129
num_features = 128
if features.shape[0] < timesteps:
    pad_width = timesteps - features.shape[0]
    features = np.pad(features, ((0, pad_width), (0, 0)), mode='constant')
else:
    features = features[:timesteps, :]

print(f"Padded MFCC shape: {features.shape}")
features = features.reshape(1, timesteps, num_features)
print(f"Final input shape: {features.shape}")

predictions = model.predict(features)
predicted_label = np.argmax(predictions)
predicted_class = emotions[predicted_label]

print("Predicted class:", predicted_class)

Original MFCC shape: (128, 73)
Transposed MFCC shape: (73, 128)
Padded MFCC shape: (129, 128)
Final input shape: (1, 129, 128)
1/1 [==============================] - 0s 156ms/step
Predicted class: OAF_Fear
